# Configuration for support-requests - https://github.com/dessant/support-requests

# Label used to mark issues as support requests
supportLabel: "type: question/stack overflow"
# Comment to post on issues marked as support requests. Add a link
# to a support page, or set to `false` to disable
supportComment: >
  We use the issue tracker exclusively for bug reports and feature requests.
  This issue appears to be a general usage or support question. 
  Instead, please ask a question on Stack Overflow with the `react-native-notifications` tag.
# Whether to close issues marked as support requests
close: true
# Whether to lock issues marked as support requests
lock: false
