require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

def all_pods
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])

  pod 'react-native-notifications', :path => '../../'
end

target 'NotificationsExampleApp' do
  all_pods
end

target 'NotificationsExampleAppTests' do
  all_pods
  pod 'OCMock'
end
