require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

def all_pods
  config = use_native_modules!
  use_react_native!(:path => config[:reactNativePath])

  pod 'react-native-notifications', :path => '../../'
end

post_install do |installer|
  __apply_Xcode_15_3_flipper_post_install_workaround(installer)

  react_native_post_install(installer, "../../node_modules/react-native", :mac_catalyst_enabled => false)

  __apply_Xcode_15_unary_binary_error_workaround(installer)

  # This is to resolve "'shared_timed_mutex' is unavailable: introduced in iOS 10.0" error
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
    end
  end
end

def __apply_Xcode_15_3_flipper_post_install_workaround(installer)
  installer.pods_project.targets.each do |target|
    if target.name == 'Flipper'
      file_path = 'Pods/Flipper/xplat/Flipper/FlipperTransportTypes.h'
      contents = File.read(file_path)
      unless contents.include?('#include <functional>')
        File.open(file_path, 'w') do |file|
          file.puts('#include <functional>')
          file.puts(contents)
        end
      end
    end
  end
end

def __apply_Xcode_15_unary_binary_error_workaround(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
    end
  end
end

target 'NotificationsExampleApp' do
  all_pods
end

target 'NotificationsExampleAppTests' do
  all_pods
  pod 'OCMock'
end
